name: publish-typescript

on:
  push:
    tags:
      - "ts-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: typescript
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run type-check
      - run: bun run test
      - run: bun run build
      - name: Configure npm registry auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@streamoid-technologies:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm publish
